#!/usr/bin/env bash
rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./css ./fonts ./img ./js ./lib ./plugin ./index.html \
  pixelastic:/var/www/talks.pixelastic.com/slides/webperfs-bbl-meetic


